### ISSUE TITLE
Block 'using adblocker', 'adblocker detected' notifications. 

### ISSUE THREAD

**Issue by notoriousturtle** [brave/ad-block#212]
For example, see: https://www.cyberciti.biz/tips/linux-unix-pause-command.html

Block 'adblocker detected' elements. 

This is annoying as much as ads are.

**Comment by jbenitosantoni** [comment]
Im having the same problem in many other websites

**Comment by snyderp** [comment]
Thanks to both of you!

@ryanbr is working hard on tackling as many of these issues as possible.  Can you take a look at this one?

@jbenitosantoni if you see other pages showing alerts, can you open issues for them here, and we'll get them sorted out?

**Comment by notoriousturtle** [comment]
@snyderp 

> if you see other pages showing alerts, can you open issues for them here, and we'll get them sorted out?

Is there a generic solution you can apply here, rather than individual sites? 

Sure this blocks things on cyberciti.biz, but theres most of the internet displaying these annoying divs, or popups now. 

Any ideas?

**Comment by snyderp** [comment]
@notoriousturtle we don't have any specific plan for this at the moment (its a situation where we're worried we'd break too much benign / user serving behavior if we tried to do interventions like this).  

However, one thing that'd be useful for us as we're figuring out plans is to see / find if there is some kind of dataset we can use to test interventions. Like if there was a site / place / etc that just catalogued sites with these kinds of issues, we could use that as ground truth to test some possibilities.  Any ideas?  Otherwise, we'll keep digging!
